<?php

/**
 * @file
 * Contains the main module code for Cookie content blocker - Media.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cookie_content_blocker_media_help(string $route_name, RouteMatchInterface $route_match): string {
  if ($route_name !== 'help.page.cookie_content_blocker_media') {
    return '';
  }

  return '<pre>' . file_get_contents(__DIR__ . '/README.md') . '</pre>';
}
